services:
  - type: web
    name: laravel-be
    env: docker
    plan: free
    region: singapore
    rootDir: BE
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: laravel-chat-secrets

