
services:
  - type: web
    name: laravel-be
    env: docker
    plan: free
    region: singapore
    rootDir: BE
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: LongKeChat

  - type: web
    name: laravel-fe
    env: static
    rootDir: FE/vue-app
    autoDeploy: true
    buildCommand: VITE_API_BASE_URL=${VITE_API_BASE_URL} npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - fromGroup: LongKeChat-FE
    routes:
      - type: rewrite
        source: /*
        destination: /index.html